- imap-types/Cargo.toml
The newest release fixes the stack overflow that
may occur for recursive types which derive `Arbitrary`.
The type `BodyStructure` was affected by this.
Fixes #61
> Update arbitrary to prevent stack overflow.

- imap-types/src/codec.rs
- imap-types/src/rfc3501/body.rs
- src/rfc3501/body.rs
> fix(misuse): Fix `Body` misuse.

- imap-types/src/utils.rs
- src/rfc3501/core.rs
> fix(misuse): Modify `text` parser to exclude `[` and `]`.

- imap-types/src/arbitrary/mod.rs
- imap-types/src/codec.rs
- imap-types/src/lib.rs
- imap-types/src/rfc3501/response.rs
- src/rfc3501/response.rs
This fixes #120. (Merge after #125.)
> fix(misuse): Introduce `CodeOther`.

- imap-types/src/rfc3501/response.rs
> fix(misuse): Fix `CapabilityOther`.

- Cargo.toml
- imap-types/Cargo.toml
- imap-types/src/command.rs
- imap-types/src/core.rs
- imap-types/src/datetime.rs
- imap-types/src/extensions.rs
- imap-types/src/extensions/enable.rs
- imap-types/src/extensions/quota.rs
- imap-types/src/lib.rs
- imap-types/src/mailbox.rs
- imap-types/src/response.rs
- imap-types/src/state.rs
- imap-types/src/status.rs
- src/codec/decode.rs
- src/codec/encode.rs
- src/command.rs
- src/core.rs
- src/extensions.rs
- src/lib.rs
This PR:
- Customizes the docs.rs build. When building the documentation docs.rs will now use `--all-features` and set the configuration flag `docsrs`. See [here](https://docs.rs/about/metadata) for reference.
-  Enables the nightly feature [doc_cfg](https://doc.rust-lang.org/unstable-book/language-features/doc-cfg.html) if the configuration flag "docsrs" is set. It allows us to add annotations to feature-gates items. For this it's necessary to build the documentation with a nightly compiler.
- Adds annotations to all feature-gates items for the features `tokio`, `unchecked`, `starttls` and `ext_*` via `doc(cfg(feature = "..."))`.
There are some caveats:
- Even though it's possible to add an annotation to a feature-gated trait implementation (`impl Foo for Bar`), that's not possible for …
> Add annotations to feature-gated items

- imap-types/src/core.rs
- imap-types/src/extensions.rs
- imap-types/src/secret.rs
- imap-types/src/state.rs
- imap-types/src/utils.rs
- src/auth.rs
- src/body.rs
- src/codec.rs
- src/command.rs
- src/core.rs
- src/datetime.rs
- src/envelope.rs
- src/extensions.rs
- src/fetch.rs
- src/flag.rs
- src/mailbox.rs
- src/response.rs
- src/search.rs
- src/section.rs
- src/sequence.rs
- src/status.rs
- src/tokio.rs
This closes #265 and #267 (for now).
> docs: Add documentation to `core` (and some other items).

- src/auth.rs
- src/body.rs
- src/codec/decode.rs
- src/command.rs
- src/core.rs
- src/datetime.rs
- src/envelope.rs
- src/extensions/compress.rs
- src/extensions/enable.rs
- src/extensions/idle.rs
- src/extensions/move.rs
- src/extensions/quota.rs
- src/fetch.rs
- src/flag.rs
- src/mailbox.rs
- src/response.rs
- src/search.rs
- src/section.rs
- src/sequence.rs
- src/status.rs
- src/testing.rs
This closes #268. (We may (re)add a `nom` feature later should anyone be interested.)
> chore: Don't export nom parsers.

- assets/demos/tokio-support/src/client.rs
- assets/demos/tokio-support/src/server.rs
- imap-codec/examples/common/common.rs
- imap-codec/examples/parse_command.rs
- imap-codec/examples/parse_greeting.rs
- imap-codec/examples/parse_response.rs
- imap-codec/fuzz/src/lib.rs
- imap-codec/src/codec.rs
- imap-codec/src/codec/decode.rs
- imap-codec/src/command.rs
- imap-codec/src/core.rs
- imap-codec/src/extensions/idle.rs
- imap-codec/src/response.rs
- imap-codec/src/testing.rs
- imap-types/src/command.rs
- imap-types/src/response.rs
I would argue the `tag` is required in `LiteralFound`, so doing this breaking change is fine.
The implementation is... peculiar. But we are limited by the current parsing architecture. The only way we can "signal" that a literal was found is through `IMAPParseError { kind: IMAPErrorKind::Literal { .. } }`. This structure can be returned in any of the deeply-nested `fn literal` parsers that don't have access to anything before, i.e., the tag.
Edit: I have a better idea: The `fn literal` parser now trusts that the upper `fn command` parser will fill in the missing `tag`. This way, we don't need to parse the `tag` twice.
What do you think, @jakoschiko?
> fix: Rework `DecodeError`.

- assets/demos/tokio-support/src/client.rs
- assets/demos/tokio-support/src/server.rs
- imap-codec/benches/parse_command.rs
- imap-codec/benches/parse_response.rs
- imap-codec/examples/parse_command.rs
- imap-codec/examples/parse_greeting.rs
- imap-codec/examples/parse_response.rs
- imap-codec/fuzz/src/lib.rs
- imap-codec/src/codec.rs
- imap-codec/src/codec/decode.rs
- imap-codec/src/extensions/idle.rs
- imap-codec/src/lib.rs
- imap-codec/src/testing.rs
- imap-codec/tests/readme.rs
- imap-codec/tests/trace.rs
* Added `&self` to `Decoder`.
* Renamed `Item` to `Message`. (I think from all options naming it `Message` is the best.)
> refactor: Refactor `Decoder`.

- imap-types/src/response.rs
> feat: Introduce `StatusV2`

- .github/workflows/api.yml
- imap-codec/Cargo.toml
- imap-codec/fuzz/Cargo.toml
- imap-codec/src/codec/encode.rs
- imap-codec/src/command.rs
- imap-codec/src/extensions.rs
- imap-codec/src/extensions/id.rs
- imap-codec/src/response.rs
- imap-types/Cargo.toml
- imap-types/src/command.rs
- imap-types/src/response.rs
> feat: Implement `ID` (RFC 2971)

- imap-codec/src/codec/decode.rs
- imap-types/src/response.rs
Closes #401 
Note: `Copy` is an API commitment. There are some `non_exhaustive` types that could already be `Copy` as well, but I'm not sure all variants will be in the future.
> feat: Implement `Copy` for some types

- imap-types/src/sequence.rs
> fix(imap-types): Fix `SequenceSetIterNaive`

- imap-codec/src/codec.rs
If I understand correctly the codec structs (e.g. `CommandCodec`) might contain options in the future that effect how messages are encoded/decoded. It's useful to implement `Clone` and `PartialEq` for such option structs. This PR does this.
Resolves #438
> feat: Implement `Clone` and `PartialEq` for codec types

- imap-codec/Cargo.toml
- imap-codec/src/mailbox.rs
- imap-codec/src/response.rs
Microsoft Exchange responds STATUS with a trailing space, which is not RFC compliant.
This is similarly worked around in Ruby's imap library: https://bugs.ruby-lang.org/issues/13649
> quirk: deal with Exchange's excessive space

- Cargo.lock
- imap-codec/Cargo.toml
- imap-codec/fuzz/Cargo.toml
- imap-codec/fuzz/fuzz_targets/tags_structured.rs
- imap-codec/src/core.rs
- imap-codec/src/lib.rs
Adds Basic Structure Aware Fuzzing for tag_imap:
- TagInput: A struct representing the input for the fuzz target.
- Arbitrary Implementation: This allows TagInput to be generated with random values.
- Conversion to Bytes: Converts the input string to bytes.
- Parsing: Attempts to parse the input bytes as an IMAP tag using tag_imap.
- Currently does not specify additional checks in the even of a parsing failure.
> Structure Aware Tag Fuzz Target

- README.md
- assets/demos/README.md
- Fix broken link to `Encoded` struct
- Update remaining `imap-flow` links to `imap-next`
> docs: Update links in README

- imap-codec/examples/common/common.rs
The `parse_*` examples for imap-codec were not running on Windows due to an incorrect conversion of an already existing `CRLF` line ending to an erroneous `CRCRLF` line ending.
This fixes the issue by ensuring a `CRLF` line ending in all possible cases.
Also, EOF of stdin is now handled and no longer results in an endless loop (e.g. `echo -n "* OK Hello" | cargo run -p imap-codec --example parse_greeting`).
> fix: Handle different line endings and EOF in examples

- imap-types/src/mailbox.rs
Previously, there were two macros named `impl_try_from` in scope in `mailbox.rs` (from import and local definition). While the build correctly resolved both macros, rust-analyzer did not and complained about using the imported macro.
Renaming the local macro resolves this ambiguity and makes rust-analyzer happy.
> fix: Resolve conflicting macro definition

- .github/workflows/audit.yml
- .github/workflows/main.yml
- justfile
- remove coverage artifacts before running the tests as well (otherwise, a failing test run may leave coverage artifacts in place)
- keep all coverage related files in `target/coverage`
- add creation of HTML report for local development use
> build: Improve coverage reporting

- justfile
Previously, coverage data could be messed up by build artifacts restored from the GitHub cache. While it is not yet cleared up how this actually happens, removing all build data before executing the coverage test run seems to resolve this issue.
This fixes #508.
> fix(build): Use clean build for coverage test run

- imap-types/src/core.rs
- imap-types/src/datetime.rs
- imap-types/src/mailbox.rs
- imap-types/src/response.rs
Previously, correctness through the existing validation functions was
not enforced during deserialization.
This is now achieved by going through `TryFrom` implementations or
specific field deserialization functions. Thus, it should no longer be
possible to create invalid instances by deserialization.
This fixes #502.
> fix(misuse): Add validation to deserialization

- justfile
Due to the missing space at the line continuation, the arguments are directly concatenated, resulting in `imap-codec-bench--all-targets` instead of separate arguments.
For the exclude parameter, this only results in a "package ... not found" warning. However, due to the missing `--all-targets` parameter, the minimal version checks are not performed over all build targets.
> fix(build): Fix arguments to minimal version check

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- bindings/imap-codec-python/.gitignore
- bindings/imap-codec-python/Cargo.toml
- bindings/imap-codec-python/imap_codec.pyi
- bindings/imap-codec-python/pyproject.toml
- bindings/imap-codec-python/src/lib.rs
- bindings/imap-codec-python/tests/test_sum_as_string.py
- deny.toml
- justfile
- This creates a new `maturin` template project for `PyO3` in which the Python bindings for imap-codec will be implemented.
- It also adds basic Python unit tests for the example function `sum_to_string` of the template project that is available from the compiled Rust code.
- By using the new `bindings` just recipe running build and test of the Python bindings can be triggered.
- A new GitHub job for automatically running the build in CI is added to the workflow.
This is part of #359.
> Create project for python bindings

- Cargo.lock
- Cargo.toml
- bindings/imap-codec-python/Cargo.toml
- deny.toml
This updates PyO3 to version 0.22.0 and removes the temporary patch for fixing the sub-dependency version requirement.
This closes #516 .
> Update PyO3 to version 0.22

- .github/dependabot.yml
> build: enable `package-ecosystem: "cargo"` for dependabot

- Cargo.lock
- imap-codec/Cargo.toml
- imap-codec/fuzz/Cargo.toml
- imap-codec/fuzz/fuzz_targets/fragmentizer.rs
- imap-codec/src/fragmentizer.rs
Run with ...
```bash
cd imap-codec
cargo +nightly fuzz run fragmentizer --features=debug --release -- -dict=fuzz/imap.dict -max_len=128
```
(Remove `--features=debug` to suppress debug output.)
> test(imap-codec): add `fragmentizer` fuzz-target

- README.md
- imap-codec/examples/fragmentizer.rs
- imap-codec/src/fragmentizer.rs
- imap-codec/src/lib.rs
Closes #538 
It makes sense to review this commit by commit.
* `docs(imap-codec): improve documentation` is unrelated. Just fixed it as I saw it.
* `style: reorder types according to "fn main first" style` is a pure move of types. imap-codec defines types top-to-bottom. This makes it more consistent.
> docs: add `Fragmentizer` docs

- bindings/imap-codec-python/imap_codec.pyi
- bindings/imap-codec-python/src/encoded.rs
- bindings/imap-codec-python/src/lib.rs
- bindings/imap-codec-python/tests/test_authenticate_data_encode.py
- bindings/imap-codec-python/tests/test_command_encode.py
- bindings/imap-codec-python/tests/test_fragments.py
- bindings/imap-codec-python/tests/test_greeting_encode.py
- bindings/imap-codec-python/tests/test_idle_done_encode.py
- bindings/imap-codec-python/tests/test_response_encode.py
This replaces the dictionaries returned by the `Encoded` iterator with individual `LineFragement` and `LiteralFragment` classes that can be handled more intuitively from the Python code.
Closes #560.
> Use separate Python classes for fragment variants

- Cargo.lock
- imap-codec/Cargo.toml
- imap-codec/src/codec/encode.rs
Since #561, the encoded fragments are no longer deserialized into Python objects. Thus `Fragment` no longer has to implement `Serialize`.
For version 2.0, we are not aiming for implementing `Serialize`/`Deserialize` for types in `imap-codec` (see #555). Thus, removing the single implementation restores consistency for the release.
> Remove serialization of `Fragment`

- imap-codec/src/sequence.rs
- imap-types/src/response.rs
Clippy 1.80.0 (2024-07-21) introduced a new lint [`doc_lazy_continuation`](https://rust-lang.github.io/rust-clippy/master/index.html#/doc_lazy_continuation) that was triggered by some of the existing doc comments. This fixes these comments.
> chore: Obey new Clippy lint

- .github/workflows/audit.yml
- .github/workflows/main.yml
As some CI jobs are required for PRs to be merged, these jobs have to be run even if only non-source file would be modified. Thus, the path filters for PR runs have to be removed.
Additionally, correctly managing the path lists turns out to be very error prone. Thus, removing them for the `main` branch seems to make more sense than keeping and managing them there.
> build: Remove CI path filters

- bindings/imap-codec-python/Cargo.toml
- bindings/imap-codec-python/pyproject.toml
This populates several metadata fields for the Python bindings that will be used by PyPI for the package.
As maturin merges metadata from `Cargo.toml` and `pyproject.toml` into the package (with higher precedence on `pyproject.toml`), compatible metadata was added to `Cargo.toml`.
This closes #557.
> build: Add metadata for Python bindings

- bindings/imap-codec-python/README.md
This adds a readme file for the Python bindings that should provide a basic overview of the library on the PyPI project page.
This closes #558.
Feel free to comment on points that I forgot to add and which you see as important for the first release.
> chore: Add readme for Python bindings

- .github/workflows/release.yml
- assets/demos/tokio-client/Cargo.toml
- assets/demos/tokio-server/Cargo.toml
- assets/demos/tokio-support/Cargo.toml
This adds a basic CI workflow for automatically publishing the Rust crates (currently `imap-codec` and `imap-types`) to crates.io when a corresponding Git tag is pushed.
For now, only the tag's version number is checked against the version number specified in the crates `Cargo.toml` file before publishing the crate is performed.
Later on, the release workflow could be further automated using crated like [`cargo-workspaces`](https://github.com/pksunkara/cargo-workspaces), [`cargo-release`](https://github.com/crate-ci/cargo-release) or [`cargo-smart-release`](https://github.com/Byron/cargo-smart-release). However, for that, a formal release workflow (when to release, which version number to bump which way and so on) has to be decided on first.
> Add CI workflow for publishing Rust crates

- Cargo.lock
- bindings/imap-codec-python/Cargo.toml
As the initial development pre-release seems to have worked as intended, we can now perform an actual release.
The package can successfully be installed from PyPI using pip:
```
> python -m pip install imap-codec
Collecting imap-codec
Downloading imap_codec-0.1.0.dev1-cp312-none-win_amd64.whl.metadata (2.7 kB)
Downloading imap_codec-0.1.0.dev1-cp312-none-win_amd64.whl (898 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 898.3/898.3 kB 3.6 MB/s eta 0:00:00
Installing collected packages: imap-codec
Successfully installed imap-codec-0.1.0.dev1
> python -m unittest                     
..............................................................
----------------------------------------------------------------------
Ran 62 tests in 0.007s
OK
```
> chore: Bump Python bindings version to 0.1.0

- .github/workflows/main.yml
- CHANGELOG.md
- CONTRIBUTING.md
- Cargo.lock
- deny.toml
- imap-codec/benchmark/Cargo.toml
- imap-codec/fuzz/Cargo.toml
- imap-types/Cargo.toml
- justfile
It's theoretically not required to update the MSRV (because we don't really use `clap`). But we probably want to increase a bit due to `Arbitrary`. As long as noone is asking for it, I took the quick path and just bumped to 1.74.
> chore: Fix failing CI

- imap-types/src/core.rs
> refactor: Use `AtomicUsize` instead of `AtomicU64` in `TagGenerator`

- imap-codec/Cargo.toml
- imap-codec/src/response.rs
> Add quirk for missing space in continue req command

- Cargo.toml
- flake.nix
- imap-codec/Cargo.toml
- imap-codec/src/mailbox.rs
- imap-codec/src/response.rs
- imap-types/Cargo.toml
- justfile
Plus small refactor of msrv handling (thanks @jakoschiko).
> refactor: Rename `quirk_trailing_space` to `quirk_trailing_space_status`
