duesee/imap-codec

assets/demos/tokio_client/src/main.rs, assets/demos/tokio_server/src/main.rs, benches/parse_command.rs, benches/parse_response.rs, examples/parse_command.rs, examples/parse_greeting.rs, examples/parse_response.rs, fuzz/fuzz_targets/command.rs, fuzz/fuzz_targets/command_to_bytes_and_back.rs, fuzz/fuzz_targets/greeting.rs, fuzz/fuzz_targets/greeting_to_bytes_and_back.rs, fuzz/fuzz_targets/response.rs, fuzz/fuzz_targets/response_to_bytes_and_back.rs, src/extensions/rfc5161.rs, src/lib.rs, src/rfc3501/command.rs, src/tokio_compat/client.rs, src/tokio_compat/server.rs, src/utils.rs, tests/readme.rs, tests/trace.rs
* Re-export imap-types::* in imap-codec.
* Do not export nom in public API.
=> Switch to new module layout in imap-codec.

Cargo.toml, imap-types/Cargo.toml, imap-types/src/arbitrary/mod.rs, imap-types/src/lib.rs, imap-types/src/rfc3501/core.rs, imap-types/src/rfc3501/mailbox.rs, imap-types/src/rfc3501/sequence.rs, imap-types/tests/api.rs, src/lib.rs, src/rfc3501/command.rs, src/rfc3501/core.rs, src/rfc3501/datetime.rs, src/rfc3501/fetch_attributes.rs, src/rfc3501/mailbox.rs, src/rfc3501/response.rs, src/rfc3501/section.rs, src/rfc3501/sequence.rs
=> Introduce `unchecked` feature and `#![forbid(unsafe_code)]`.

CHANGELOG.md, imap-types/Cargo.toml, imap-types/fuzz/Cargo.toml, imap-types/src/arbitrary/mod.rs, imap-types/src/codec.rs, imap-types/src/extensions/mod.rs, imap-types/src/extensions/rfc9208.rs, imap-types/src/lib.rs, imap-types/src/rfc3501/command.rs, imap-types/src/rfc3501/response.rs, imap-types/src/rfc3501/sequence.rs, imap-types/src/rfc3501/status_attributes.rs
This work is based on the implementation provided in #90.
=> feat: Implement support for RFC 9208 (Quota)

Cargo.toml, fuzz/Cargo.toml, src/extensions/mod.rs, src/extensions/rfc9208.rs, src/lib.rs, src/rfc3501/command.rs, src/rfc3501/core.rs, src/rfc3501/mailbox.rs, src/rfc3501/response.rs, src/rfc3501/status_attributes.rs
=> feat: Implement RFC 9208 (Quota) in imap-codec.

imap-types/src/rfc3501/response.rs, src/extensions/rfc9208.rs, src/rfc3501/response.rs
=> fix(misuse): Fix QUOTA misuse.

src/lib.rs
=> docs: Add `ext_sasl_ir` feature to documentation.

Cargo.toml, fuzz/Cargo.toml, fuzz/fuzz_targets/greeting_to_bytes_and_back.rs, fuzz/fuzz_targets/response_to_bytes_and_back.rs, imap-types/Cargo.toml, imap-types/fuzz/Cargo.toml, imap-types/src/codec.rs, imap-types/src/rfc3501/response.rs, src/lib.rs, src/rfc3501/response.rs
=> build: Feature-gate `ext_{login,mailbox}_referrals`.

fuzz/Cargo.toml, fuzz/fuzz_targets/command.rs, fuzz/fuzz_targets/command_to_bytes_and_back.rs, fuzz/fuzz_targets/greeting.rs, fuzz/fuzz_targets/greeting_to_bytes_and_back.rs, fuzz/fuzz_targets/response.rs, fuzz/fuzz_targets/response_to_bytes_and_back.rs, imap-types/fuzz/Cargo.toml, imap-types/src/rfc3501/body.rs, imap-types/src/rfc3501/response.rs, src/lib.rs, src/utils.rs
=> test: Improve fuzz-targets.

imap-types/Cargo.toml, imap-types/src/codec.rs, imap-types/src/extensions/rfc4987.rs, imap-types/src/extensions/rfc9208.rs, imap-types/src/lib.rs, imap-types/src/rfc3501/body.rs, imap-types/src/rfc3501/command.rs, imap-types/src/rfc3501/core.rs, imap-types/src/rfc3501/mailbox.rs, imap-types/src/rfc3501/mod.rs, imap-types/src/rfc3501/response.rs, imap-types/src/rfc3501/sequence.rs, imap-types/tests/api.rs, src/rfc3501/command.rs, tests/trace.rs
=> feat: Improve error reporting (+ chore).

imap-types/src/codec.rs, imap-types/src/lib.rs, imap-types/src/rfc3501/sequence.rs, src/rfc3501/command.rs, src/rfc3501/sequence.rs
=> refactor: Rename `SeqNo` -> `SeqOrUid`, `SeqNo::largest` -> `SeqNo::Asterisk`.

fuzz/fuzz_targets/command_to_bytes_and_back.rs, fuzz/fuzz_targets/greeting_to_bytes_and_back.rs, fuzz/fuzz_targets/response_to_bytes_and_back.rs, imap-types/src/arbitrary/mod.rs, imap-types/src/codec.rs, imap-types/src/lib.rs, imap-types/src/rfc3501/core.rs, imap-types/src/rfc3501/fetch_attributes.rs, imap-types/src/rfc3501/flag.rs, imap-types/src/rfc3501/response.rs, src/rfc3501/flag.rs, tests/trace.rs
=> fix: Fix flag handling.

fuzz/fuzz_targets/command_to_bytes_and_back.rs, fuzz/fuzz_targets/greeting_to_bytes_and_back.rs, imap-types/src/rfc3501/envelope.rs, src/rfc3501/envelope.rs
=> chore: Cleanup Envelope + chore.

Cargo.toml, imap-types/src/rfc3501/flag.rs, src/rfc3501/flag.rs
=> fix: Fix `mbx_list_flags`.

fuzz/README.md, fuzz/fuzz_targets/command_to_bytes_and_back.rs, imap-types/Cargo.toml, imap-types/src/arbitrary.rs, imap-types/src/codec.rs, imap-types/src/imap4rev1/command.rs, imap-types/src/imap4rev1/command/search.rs, imap-types/src/imap4rev1/datetime.rs, imap-types/src/imap4rev1/fetch_attributes.rs, imap-types/src/state.rs, src/imap4rev1/command/search.rs, src/imap4rev1/datetime.rs, tests/trace.rs
This also solves a part of #30.
=> Narrow allowed values for `DateTime` and `NaiveDate`. 

imap-types/src/imap4rev1/command.rs, imap-types/src/security.rs
=> feat: Implement `From<T>` for `Secret` (+ chore).

src/imap4rev1/response.rs, src/lib.rs, src/testing.rs
=> fix: Fix possible panic! in response.

Cargo.toml, fuzz/Cargo.toml, imap-types/Cargo.toml, imap-types/fuzz/Cargo.toml, imap-types/src/extensions/enable.rs, imap-types/src/imap4rev1/status_attributes.rs, src/codec/encode.rs, src/extensions/enable.rs, src/imap4rev1/command/search.rs, src/imap4rev1/status_attributes.rs, src/lib.rs
=> feat: Implement `CONDSTORE` / `QRESYNC` (1/N).

.github/workflows/build_and_test.yml, assets/demos/tokio_server/src/main.rs, imap-types/src/imap4rev1/command.rs, imap-types/src/lib.rs, imap-types/src/secret.rs, imap-types/tests/readme.rs, src/codec/encode.rs, src/imap4rev1/command.rs, src/lib.rs, src/tokio/server.rs, tests/trace.rs
=> fix: Fix `Eq` side effect of `Secret`.

README.md, benches/serialize_command.rs, benches/serialize_response.rs, fuzz/fuzz_targets/command.rs, fuzz/fuzz_targets/command_to_bytes_and_back.rs, fuzz/fuzz_targets/greeting.rs, fuzz/fuzz_targets/greeting_to_bytes_and_back.rs, fuzz/fuzz_targets/response.rs, fuzz/fuzz_targets/response_to_bytes_and_back.rs, imap-types/src/lib.rs, imap-types/src/secret.rs, imap-types/src/utils.rs, src/codec.rs, src/codec/encode.rs, src/extensions/compress.rs, src/extensions/enable.rs, src/extensions/idle.rs, src/extensions/literal.rs, src/extensions/quota.rs, src/imap4rev1/command.rs, src/imap4rev1/core.rs, src/imap4rev1/sequence.rs, src/lib.rs, src/testing.rs, src/tokio/client.rs, src/tokio/server.rs, tests/readme.rs, tests/trace.rs
=> feat: Redesign Encode trait.

imap-types/src/arbitrary.rs, imap-types/src/body.rs, imap-types/src/lib.rs, src/body.rs, src/codec.rs, src/codec/encode.rs, src/extensions/compress.rs, src/extensions/enable.rs, src/extensions/idle.rs, src/extensions/literal.rs, src/extensions/quota.rs, src/response.rs
=>  refactor: Rename `SpecificFields::Basic.type_` to `SpecificFields::Basic.type` (+ chore).

imap-types/src/command.rs, imap-types/src/response.rs, src/command.rs, src/extensions/quota.rs, src/mailbox.rs
This is only a small improvement but closes #240 for now.
=> feat: Use `Cow<[T]>` in `{Command,Data}::Status`.

README.md
=> docs: Update `README.md`.

Cargo.toml, fuzz/Cargo.toml, src/auth.rs, src/command.rs, src/core.rs, src/extensions/idle.rs, src/response.rs, src/tokio.rs, src/tokio/client.rs, src/tokio/server.rs
=> feat: Introduce `quirk_crlf_relaxed` feature.

imap-types/src/command.rs, imap-types/src/secret.rs, src/codec/encode.rs
=> refactor: Introduce `CommandBody::authenticate_with_ir`.

.github/workflows/build_and_test.yml, Cargo.toml, README.md, assets/demos/tokio-client/Cargo.toml, assets/demos/tokio-client/src/main.rs, assets/demos/tokio-server/Cargo.toml, assets/demos/tokio-server/src/main.rs, fuzz/Cargo.toml, imap-types/Cargo.toml, imap-types/README.md, imap-types/fuzz/Cargo.toml, imap-types/src/arbitrary.rs, imap-types/src/mailbox.rs, imap-types/src/secret.rs, src/codec.rs, src/codec/decode.rs, src/codec/encode.rs, src/lib.rs
=> chore: Remove constant-time comparison support.

imap-codec/src/codec/encode.rs, imap-codec/src/flag.rs, imap-types/src/arbitrary.rs, imap-types/src/flag.rs
=> fix(misuse): Introduce `FlagNameAttributeExtension`.

imap-codec/src/response.rs, imap-types/src/core.rs
=> work: Improvements due to work on `imap-flow`

imap-codec/src/auth.rs, imap-codec/src/body.rs, imap-codec/src/codec.rs, imap-codec/src/codec/decode.rs, imap-codec/src/codec/encode.rs, imap-codec/src/core.rs, imap-types/src/auth.rs, imap-types/src/secret.rs, imap-types/src/sequence.rs
Closes #411 (https://github.com/duesee/imap-codec/pull/416/commits/50c469112ca021ad911bde2493d574fd2ee432b6)
=> feat: More from `v2`

assets/demos/tokio-server/src/main.rs, imap-codec/src/body.rs, imap-codec/src/codec.rs, imap-codec/src/codec/decode.rs, imap-codec/src/codec/encode.rs, imap-codec/src/extensions/literal.rs, imap-codec/src/extensions/quota.rs, imap-codec/src/extensions/sort.rs, imap-codec/src/fetch.rs, imap-codec/src/response.rs, imap-codec/src/search.rs, imap-codec/src/sequence.rs, imap-types/src/arbitrary.rs, imap-types/src/body.rs, imap-types/src/command.rs, imap-types/src/core.rs, imap-types/src/error.rs, imap-types/src/extensions/enable.rs, imap-types/src/extensions/quota.rs, imap-types/src/fetch.rs, imap-types/src/lib.rs, imap-types/src/response.rs, imap-types/src/search.rs, imap-types/src/sequence.rs
=>  refactor!,feat: Replace `NonEmptyVec` with `Vec1`

.github/workflows/build_and_test.yml, imap-codec/Cargo.toml, imap-codec/fuzz/Cargo.toml, imap-codec/src/codec/encode.rs, imap-codec/src/command.rs, imap-codec/src/extensions.rs, imap-codec/src/extensions/binary.rs, imap-codec/src/extensions/metadata.rs, imap-codec/src/mailbox.rs, imap-codec/src/response.rs, imap-codec/src/testing.rs, imap-types/Cargo.toml, imap-types/fuzz/Cargo.toml, imap-types/src/command.rs, imap-types/src/extensions.rs, imap-types/src/extensions/enable.rs, imap-types/src/extensions/metadata.rs, imap-types/src/lib.rs, imap-types/src/response.rs
=> feat: Implement `METADATA`

README.md, imap-codec/fuzz/README.md
=> docs: Update README and fuzz/README

imap-types/src/arbitrary.rs, imap-types/src/extensions/thread.rs
=> tests: Use custom `Arbitrary` impl for `Thread`

CONTRIBUTING.md
=> docs: Update `CONTRIBUTING.md`

imap-types/src/core.rs, imap-types/src/datetime.rs, imap-types/src/mailbox.rs
=> docs: Add note about panic! in T::unvalidated (+ fix)

.github/workflows/build_and_test.yml, imap-codec/fuzz/Cargo.toml, imap-types/Cargo.toml, imap-types/src/arbitrary.rs, imap-types/src/extensions/sort.rs, imap-types/src/extensions/thread.rs
=> tests: Add `arbitrary_simplified` feature

imap-codec/Cargo.toml, imap-codec/fuzz/Cargo.toml, imap-codec/src/codec/encode.rs, imap-codec/src/command.rs, imap-codec/src/extensions.rs, imap-codec/src/extensions/uidplus.rs, imap-codec/src/response.rs, imap-types/Cargo.toml, imap-types/fuzz/Cargo.toml, imap-types/src/command.rs, imap-types/src/extensions.rs, imap-types/src/extensions/uidplus.rs, imap-types/src/response.rs
=> feat: implement `UIDPLUS`

.gitignore, flake.lock, flake.nix, rust-toolchain.toml, shell.nix
Analogous to https://github.com/duesee/imap-flow/pull/173.
=> Add basic Nix support

imap-types/src/command.rs, imap-types/src/core.rs, imap-types/src/extensions/compress.rs, imap-types/src/extensions/enable.rs, imap-types/src/extensions/move.rs, imap-types/src/extensions/quota.rs, imap-types/src/extensions/unselect.rs, imap-types/src/lib.rs
=> docs(imap-types): describe required capabilities in API

imap-codec/examples/fragmentizer_client.rs, imap-codec/examples/fragmentizer_server.rs, imap-codec/src/fragmentizer.rs, imap-codec/src/lib.rs
Closes #536. This is only a move (with minor required changes to imports.)
* ~Move fuzz-target~ Nevermind. Not pushed to imap-next so far.
=> feat: Use `Fragmentizer` from `imap-next`

imap-codec/src/codec/encode.rs
Fixes the performance issue mentioned in #535
=> perf(imap-codec): Fix quadratic runtime when iterating `Encoded`

Cargo.lock, imap-codec/Cargo.toml, imap-codec/examples/fragmentizer_client.rs, imap-codec/examples/fragmentizer_server.rs, imap-codec/fuzz/Cargo.toml, imap-codec/fuzz/fuzz_targets/fragmentizer.rs, imap-codec/src/fragmentizer.rs
Just something to discuss. What do you think @jakoschiko?
=> refactor: Remove `MaxMessageSize`

assets/demos/tokio-support/Cargo.toml, assets/demos/tokio-support/src/server.rs, bindings/imap-codec-python/Cargo.toml, imap-codec/Cargo.toml, imap-codec/fuzz/Cargo.toml, imap-codec/src/codec/encode.rs, imap-codec/src/command.rs, imap-codec/src/extensions.rs, imap-codec/src/fetch.rs, imap-codec/src/mailbox.rs, imap-codec/src/response.rs, imap-codec/src/search.rs, imap-codec/tests/trace.rs, imap-types/Cargo.toml, imap-types/README.md, imap-types/fuzz/Cargo.toml, imap-types/src/command.rs, imap-types/src/core.rs, imap-types/src/datetime.rs, imap-types/src/extensions.rs, imap-types/src/extensions/thread.rs, imap-types/src/fetch.rs, imap-types/src/lib.rs, imap-types/src/mailbox.rs, imap-types/src/response.rs, imap-types/tests/api.rs, imap-types/tests/readme.rs, justfile
* Closes #512
* Closes #548
* Closes #552 
Let's continue here after #517.
=> Work on feature-gates

imap-types/Cargo.toml, imap-types/src/core.rs, imap-types/src/lib.rs, justfile
=> feat: add `TagGenerator`

Cargo.lock, deny.toml, imap-codec/src/codec/decode.rs, imap-codec/src/codec/encode.rs, imap-codec/src/extensions/binary.rs, imap-codec/src/extensions/enable.rs, imap-codec/src/extensions/metadata.rs, imap-codec/src/extensions/quota.rs, imap-codec/src/extensions/thread.rs, imap-codec/src/testing.rs, imap-types/src/auth.rs, imap-types/src/command.rs, imap-types/src/core.rs, imap-types/src/extensions/binary.rs, imap-types/src/extensions/compress.rs, imap-types/src/extensions/enable.rs, imap-types/src/extensions/quota.rs, imap-types/src/extensions/thread.rs, imap-types/src/fetch.rs, imap-types/src/flag.rs, imap-types/src/mailbox.rs, imap-types/src/response.rs, imap-types/src/search.rs
I noticed some CI failures when creating PR #625 that are unrelated to the PR itself. This PR includes fixes for these failures.
=> CI failure fixes

imap-types/src/core.rs, imap-types/src/flag.rs
I noticed some really minor pain points while using the API some days ago, so here are some fixes for it.
The major pain points would take much more time to address, unfortunately.
=> imap-types: small quality of life API improvements

imap-codec/src/codec/encode.rs, imap-codec/src/extensions.rs, imap-codec/src/extensions/condstore_qresync.rs, imap-codec/src/flag.rs, imap-codec/src/response.rs, imap-types/src/mailbox.rs, imap-types/src/response.rs
This is a rebase of https://github.com/duesee/imap-codec/pull/439 with the comments resolved and minor refactorings (move of code). Thanks again, @superboum! I'll use your bullet points in https://github.com/duesee/imap-codec/issues/196 to track our progress :-)
=> feat: Implement Condstore Status Codes

imap-codec/src/codec.rs, imap-codec/src/codec/decode.rs, imap-codec/src/codec/encode.rs, imap-codec/src/command.rs, imap-codec/src/extensions/condstore_qresync.rs, imap-codec/src/fetch.rs, imap-codec/src/mailbox.rs, imap-codec/src/response.rs, imap-codec/src/search.rs, imap-types/src/arbitrary.rs, imap-types/src/command.rs, imap-types/src/extensions.rs, imap-types/src/extensions/condstore_qresync.rs, imap-types/src/fetch.rs, imap-types/src/response.rs, imap-types/src/search.rs
=> feat: Implement CONDSTORE/QRESYNC (3/N)

imap-codec/Cargo.toml, imap-codec/src/body.rs
=> Add quirk for encoding NIL body-fld-enc to empty istring
